class Commands:

    SHELL_COMMAND = "SHELL"
    LOGIN_COMMAND = "LOGIN"
    LOGOUT_COMMAND = "LOGOUT"
    CLEAR_COMMAND = "CLEAR"
    SHOW_COMMAND = "SHOW"
    HELP_COMMAND = "HELP"

    ERROR = "ERROR"
